mode: ll
target_width: 45
target_height: 250
tolerance_width: 5
tolerance_height: 5
calibration:
  pattern_size: [9, 6]
output_path: data
save_interval_time: 10
host: 0.0.0.0
web_port: 5005
opcua_server_url: "random.omg"